services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  api:
    build: .
    container_name: inventory_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge