spring.application.name=controleestoque

# Configurações do Banco de Dados H2 (Em memória para Desenvolvimento)
spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilita o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Desativa temporariamente a inicialização automática do Docker Compose
spring.docker.compose.enabled=false